#!/usr/bin/env python3.12
"""Sync semantics/catalog SoT → frontend bundle + JS vocab (no drift)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "semantics" / "catalog"
SEM_DIR = ROOT / "frontend" / "src" / "semantics"
OUT_BUNDLE = SEM_DIR / "bundle.json"
OUT_VOCAB = SEM_DIR / "vocab.js"


def main() -> None:
    index = json.loads((CATALOG / "index.json").read_text(encoding="utf-8"))
    types = {}
    for tipo, fname in index["files"].items():
        types[tipo] = json.loads((CATALOG / fname).read_text(encoding="utf-8"))

    tip = types["tip-chip"]
    tip_ids = tip["fields"]["tipId"]["enum"]
    tip_labels = tip["tipLabels"]

    bundle = {
        "id": index["id"],
        "version": index["version"],
        "typesOrder": index["types"],
        "outOfCatalog": index["outOfCatalog"],
        "turnEnvelope": index["turnEnvelope"],
        "types": types,
    }
    SEM_DIR.mkdir(parents=True, exist_ok=True)
    OUT_BUNDLE.write_text(json.dumps(bundle, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    vocab = f"""// aiuxer@{index["version"]} | generated by tools/sync-semantics.py — DO NOT EDIT BY HAND
// Source of truth: semantics/catalog/
export const CATALOG_VERSION = {json.dumps(index["version"])};
export const TIPI_CATALOGO_LIST = Object.freeze({json.dumps(index["types"])});
export const TIPI_CATALOGO = new Set(TIPI_CATALOGO_LIST);
export const TIP_IDS = Object.freeze({json.dumps(tip_ids)});
export const TIP_LABEL = Object.freeze({json.dumps(tip_labels, ensure_ascii=False)});
export const OUT_OF_CATALOG = Object.freeze({json.dumps(index["outOfCatalog"])});
"""
    OUT_VOCAB.write_text(vocab, encoding="utf-8")
    print(f"wrote {OUT_BUNDLE.relative_to(ROOT)}")
    print(f"wrote {OUT_VOCAB.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
