// aiuxer@0.3.2 | generated by tools/sync-semantics.py — DO NOT EDIT BY HAND
// Source of truth: semantics/catalog/
export const CATALOG_VERSION = "0.3.2";
export const TIPI_CATALOGO_LIST = Object.freeze(["greeting", "faq-card", "tip-chip"]);
export const TIPI_CATALOGO = new Set(TIPI_CATALOGO_LIST);
export const TIP_IDS = Object.freeze(["what-is-this", "who-are-you", "twins", "genui-band", "memory", "how-to-talk"]);
export const TIP_LABEL = Object.freeze({"what-is-this": "What is this?", "who-are-you": "Who are you?", "twins": "The twins", "genui-band": "GenUI band", "memory": "Memory", "how-to-talk": "How to talk"});
export const OUT_OF_CATALOG = Object.freeze(["shell-header", "user-bubble", "agent-turn-prosa", "composer", "memory-panel"]);
